export const dropdown2Options = {
  // Nut: ["Roasted", "Raw", "Chopped"],
  Coffee: ["Machine Name", "Type"],
  Fruit: ["MType", "MachineMaterial", "Machine Name", "Manufacturer"],
  Grain: ["Grain", "Machine Name", "Grain Manufacturer"],
  "Ice-cream": ["Capacity", "Machine Name"],
  Juice: ["Material", "Machine Name", "Type of Juicer"],
};

export const dropdown3Options = {
  // Nut: {
  //   Roasted: ["Option 1", "Option 2", "Option 3"],
  //   Raw: ["Option 1", "Option 2", "Option 3"],
  //   Chopped: ["Option 1", "Option 2", "Option 3"],
  // },

  Coffee: {
    "Machine Name": [
      "Aeropress Go",
      "Ascaso Dream PID",
      "BALMUDA The Brew",
      "Behmor Connected Coffee Maker",
      "Bella Pro Dual Brew 90192",
      "Black+Decker CM1160B",
      "Bonaverde Berlin",
      "Bonavita Connoisseur BV1901TS",
      "Bosch Tassimo My Way TAS6002GB",
      "Breville Bambino Plus BES500BSS",
      "Breville Barista Express BES870XL",
      "Breville Barista Pro BES878BSS",
      "Breville Barista Touch BES880BSS",
      "Breville Café Roma ESP8XL",
      "Breville Duo-Temp Pro BES810",
      "Breville Grind Control",
      "Breville Oracle Touch BES990BSS",
      "Breville Precision Brewer BDC455",
      "Breville Smart Grinder Pro BCG820BSS",
      "Bunn Speed Brew Elite CSB2B",
      "Café Smart Drip C7CDAAS3PD3",
      "Café Specialty Grind & Brew Coffee Maker (C7CGAAS4TW3)",
      "Cafflano Kompact",
      "Capresso Café TS Espresso 124.01",
      "Capresso Steam PRO 304.01",
      "Cuisinart Burr Grind & Brew DGB-900BC",
      "Cuisinart Coffee Center Barista Bar 4-in-1 (SS-4N1)",
      "Cuisinart Coffee on Demand DCC-3000",
      "Cuisinart PerfecTemp DCC-3200P1",
      "Cuisinart Single Serve SS-10P1",
      "DeLonghi All-in-One Combination Coffee Maker (COM532M)",
      "De'Longhi Dedica EC685M",
      "De'Longhi EC860",
      "De'Longhi Lattissima Pro EN750MB",
      "De'Longhi Magnifica Plus ECAM32070SB",
      "De'Longhi PrimaDonna Elite ECAM650.55MS",
      "Delter Coffee Press",
      "Drink Morning Coffee Maker",
      "Dualit Espress-auto 84460",
      "Espressione Concierge 8212S",
      "Fellow Ode Brew Grinder",
      "Gaggia Brera Super Automatic",
      "Gaggia Classic Pro RI9380/46",
      "GE Café Specialty Drip Coffee Maker C7CDAAS2PBS1",
      "Hamilton Beach 2-Way Brewer 49980A",
      "Hamilton Beach FlexBrew 49976",
      "Hamilton Beach FlexBrew Single Serve 49974",
      "Hario V60 Drip Decanter",
      "Illy Y3.3 Iperespresso",
      "Jura A1 Super Automatic",
      "Jura ENA 8 Nordic White 15281",
      "Jura GIGA 10 Specialty Coffee Machine",
      "Jura Impressa E8 15226",
      "Jura Z10 15476",
      "Kalita Coffee Machine CM-102",
      "Kalita Wave 185 Dripper",
      "Keurig K-Elite",
      "Keurig K-Express Essentials",
      "Keurig K-Slim K910",
      "Keurig K-Supreme Plus SMART KSC84",
      "KitchenAid Cold Brew Coffee Maker KCM5912SX",
      "KitchenAid KCM1209OB",
      "Krups EA8298 Super Automatic",
      "Krups Simply Brew Compact Drip KM202850",
      "La Pavoni Europiccola EPC-8",
      "La Specialista Arte EC9155MB",
      "Melitta AromaFresh Grind and Brew 1021-01",
      "Melitta Barista TS Smart F85/0-102",
      "Miele CM5300",
      "Miele CM6350",
      "Mr. Coffee All-in-One Occasions BVMC-O-CT",
      "Nespresso Atelier",
      "Nespresso Creatista Plus",
      "Nespresso Creatista Pro BNE900",
      "Nespresso Essenza Mini D30",
      "Nespresso Expert C80-D80",
      "Nespresso Gran Maestria Titanium",
      "Nespresso Maestria Crema",
      "Nespresso Pixie C61",
      "Nespresso Vertuo Next",
      "Nespresso Vertuo Pop",
      "Ninja CE251",
      "Ninja DualBrew Pro CFP301",
      "Ninja Hot and Cold Brewed System CP307",
      "Ninja Specialty Coffee Maker CM401",
      "Nuova Simonelli Oscar II",
      "Oster Optimal Brew BVSTBXT43",
      "OXO Brew 8-Cup Coffee Maker",
      "Philips 3200 Series EP3241/54",
      "Philips L'OR Barista Sublime LM9012/60",
      "Rancilio Silvia V6",
      "Ratio Four Coffee Maker (RATIO4BLK)",
      "Ratio Six Coffee Maker",
      "Rocket Espresso Appartamento",
      "Sage The Bambino SES500",
      "Smeg BCC13",
      "Smeg Drip Filter Coffee Machine DCF02",
      "Smeg ECF01BLUS",
      "Solis Barista Perfetta Plus",
      "Tchibo Fully Automatic Coffee & Espresso Machine 61222",
      "Technivorm Cup-One 69212",
      "Technivorm Grand Moccamaster CDT",
      "Technivorm Moccamaster KBGT 79112",
      "Technivorm Moccamaster KBGV Select",
      "Wilfa Svart Precision WSP-2A",
      "Wolf Gourmet Programmable Coffee System WGCM100S",
      "xBloom Coffee Machine",
      "Zojirushi Fresh Brew Plus EC-YTC100XB",
      "Zojirushi Zutto Coffee Maker EC-DAC50",
    ],
    Type: [
      "Manual Press",
      "Espresso",
      "Drip",
      "Single Serve Coffee Maker",
      "Roast, Grind, Brew",
      "Drip Coffee Maker",
      "Pod",
      "Manual Espresso Machine",
      "Espresso Machine with Grinder",
      "Semi-Automatic Espresso Machine",
      "Drip Coffee Maker with Grinder",
      "Fully Automatic Espresso Machine",
      "Grind",
      "Smart Drip Coffee Maker",
      "Bean-to-cup Grinder and Drip Coffee",
      "Manual",
      "Steam Espresso Maker",
      "Drip, Single-Serve, and Espresso Capsule Machine",
      "Single Serve",
      "Drip & Espresso Machine",
      "Fully Automatic Coffee Machine",
      "Super Automatic",
      "Drip/Single Serve",
      "Dual Coffee Maker",
      "Manual Drip",
      "Espresso Machine",
      "Fully Automatic Espresso & Coffee Machine",
      "Single-Serve Pod Machine",
      "Pod-Based Coffee Maker",
      "Cold Brew Coffee Maker",
      "Manual Espresso",
      "Grind and Brew",
      "Bean-to-Cup Coffee Machine",
      "Superautomatic",
      "Drip/Espresso",
      "Capsule Coffee Machine",
      "Pod-Based Espresso Machine",
      "Compact Pod-Based Coffee Maker",
      "Programmable Coffee Brewer",
      "Drip & Pod Combo Machine",
      "Versatile Coffee and Tea Maker",
      "Drip/Specialty",
      "Pour-over Coffee Maker",
      "Manual Espresso Maker",
      "Bean-to-Cup Machine",
      "Automated Pour-over",
      "Thermal Carafe Coffee Maker",
    ],
  },

  Fruit: {
    Manufacturer: [
      "Robot Coupe",
      "Goldcheer Machinery",
      "ProFruit Machinery",
      "Beyond Machinery",
      "Jinyuan Food Machinery",
      "Kronitek",
      "Lingwood Machinery",
      "Quadra Machinery",
      "GEM Foodtech",
      "Taizy Machinery",
      "Lakewood Process",
      "Buhler Group",
      "GEA Group",
      "Multivac",
      "Alfa Laval",
      "JBT Corporation",
      "Bühler Group",
      "Kiremko",
      "Tetra Pak",
      "Heat and Control",
      "CFT Group",
      "Marel",
      "Lyco Manufacturing",
      "TOMRA Sorting Solutions",
      "FENCO Food Machinery",
      "Cabinplant",
      "Kronen GmbH",
      "Sormac",
      "FTNON",
      "Urschel Laboratories",
      "Bucher Industries",
    ],
    MachineMaterial: [
      "Stainless Steel",
      "Aluminum Alloy",
      "Stainless steel, hygienic-grade fixings",
      "Stainless steel",
      "High-grade polymer and steel",
      "Food-grade stainless steel",
      "Advanced polymers and metal alloys",
      "Stainless steel with polymer sealing elements",
      "High-strength steel and polymer",
      "Stainless steel and durable composites",
      "Stainless steel with optical components",
      "Food-grade steel",
      "Stainless steel with polymer linings",
      "Stainless steel and polymer composites",
      "Stainless steel and durable plastics",
      "Stainless steel and polymer elements",
      "Stainless steel with reinforced blades",
      "Stainless steel and food-grade polymers",
      "Stainless steel and plastic components",
    ],
    MType: [
      "Cutting",
      "Cleaning",
      "Washing",
      "Cutting/Dicing",
      "Slicing",
      "Drying",
      "Pulping",
      "Slicing/Frying",
      "Peeling/Cutting",
      "Sorting",
      "Grinding",
      "Coring/Peeling",
      "Optical Sorter",
      "Fruit & Vegetable Washer and Sorter",
      "Packaging Machine",
      "Centrifuge Separator",
      "Cold-Extracted Juice Processing System",
      "Juicer & Separator",
      "Optical Sorting Technology",
      "Tray Sealer",
      "Potato Peeler",
      "Vegetable Cutter",
      "Air Fryer Processing Line",
      "Washing Machine",
      "Vegetable Chopper",
      "Blanching Machine",
      "Juice Extractor",
      "Feeding Conveyor",
      "Vegetable Dryer",
      "Carrot Topper and Tailer",
      "Centrifugal Separator",
      "High-Pressure Processor",
      "Rotary Peeler",
      "Dicer",
      "Juice Press",
      "Coating Machine",
      "Cooling System",
      "Peeler and Sorter",
      "Conveyor System",
      "Chamber Vacuum Sealer",
      "Frying System",
      "Pasteurizer",
      "Fruit & Vegetable Washer",
      "High-Speed Washer",
      "Blender and Mixer",
      "Mixer",
      "Cold Press Juice Extractor",
      "Weighing Machine",
      "Washing and Sorting Unit",
      "Grinder",
      "Chopping Line",
    ],
    "Machine Name": [
      "CL60 Vegetable Processor",
      "Fruit Brush Cleaner",
      "Vegetable Washer",
      "Spiral Conveyor Washer",
      "Multifunction Vegetable Slicer",
      "Industrial Veg. Washer GEWA 5000V",
      "Fruit & Veg Slicing Machine Tona V",
      "Spin Dryer Basket System",
      "Mango Pulper",
      "French Fries Processing Line",
      "Universal Food Processor S40",
      "Garlic Peeler & Cutter",
      "Automatic Sorting Conveyor Line",
      "Coconut Powder Grinder",
      "Pineapple Core Remover",
      "SORTEX FA-1200",
      "GEA MaxiSort Pro",
      "Multivac R245",
      "Alfa Laval Decanter ALD-300",
      "READYGo FVP",
      "FVPGrow Juicer",
      "SORTEX PolarVision",
      "Multivac T700",
      "Kiremko Potato Peeler KP1000",
      "Tetra Pak Vegetable Cutter VC-300",
      "Heat and Control AirFry 1000",
      "CFT Group Hydra Washer",
      "Marel VeggieLine Chopper 200",
      "Lyco Manufacturing Clean-Flow Blancher",
      "TOMRA Halo 1200",
      "FENCO FM-3000",
      "Cabinplant Vibro Feeder VF-100",
      "Kronen K650 Centrifuge",
      "Sormac SC-940",
      "Alfa Laval FreshX500",
      "JBT Avure HPP-300",
      "FTNON Peeler FP-200",
      "Urschel Affinity Dicer",
      "Bucher HPX-3000",
      "Marel FlowBreader 400",
      "Lyco Chill-Flow Cooler",
      "GEA SmartPacker CX400",
      "Tetra Pak Juice Extractor JE-5000",
      "TOMRA Orbit 800",
      "Heat and Control FastBack 260E",
      "Multivac C500",
      "Kiremko EasyFry E1000",
      "FENCO PLV-5000",
      "Cabinplant Spiral Washer SW-300",
      "FTNON VeggieJet 2500",
      "GEA GracoMix GMX-10",
      "Tetra Pak High Shear Mixer HSX-6000",
      "Alfa Laval Cold Press CP-4000",
      "TOMRA Blizzard IQF Sorter",
      "Cabinplant Portion Weigher PW-2000",
      "Kronen KS-800 Spin Dryer",
      "Sormac WSU-1000",
      "GEA CombiGrind 280",
      "FTNON Cutting Line CL-1500",
    ],
  },

  Grain: {
    Grain: ["Wheat", "Rice", "Oats", "Corn"],
    "Machine Name": [
      "Wheat Flour Milling Machine",
      "Rice Huller Machine",
      "Oat Flaking Machine",
      "Corn Milling Machine",
      "Wheat De-stoner",
      "Rice Polishing Machine",
      "Oat De-hulling Machine",
      "Corn Dryer",
      "Wheat Bran Separator",
      "Rice Grading Machine",
      "Oat Groat Cutter",
      "Corn Peeling Machine",
      "Wheat Cleaning Machine",
      "Rice Whitener",
      "Oat Rolling Machine",
      "Corn Grits Machine",
      "Wheat Blending Machine",
      "Rice Husker",
      "Oat Steam Conditioner",
      "Corn Steeping Tank",
      "Wheat Grader",
      "Rice Sifter",
      "Oat Sheller",
      "Corn Grinder",
      "Wheat Separator",
      "Rice Dryer",
      "Oat Mill",
      "Corn Degerminator",
      "Wheat Washer",
      "Rice Destoner",
      "Oat Flour Mill",
      "Corn Puffing Machine",
      "Wheat Scourer",
      "Rice Whitening Machine",
      "Oat Bran Finisher",
      "Corn Flour Machine",
      "Wheat Peeler",
      "Rice Silky Polisher",
      "Oat Grain Polisher",
      "Wheat Impactor",
      "Rice Separator",
      "Corn Cooking Tank",
      "Wheat Conditioning Machine",
      "Rice Milling Machine",
      "Oat Husking Machine",
      "Corn Flaking Machine",
      "Wheat Whitening Machine",
      "Rice Sorter",
      "Oat Flour Milling Machine",
      "Corn Wet Milling Machine",
      "Wheat Polishing Machine",
      "Rice Thresher",
      "Corn Extruder",
      "Wheat Sieving Machine",
      "Rice Hull Separator",
      "Oat Bran Milling Machine",
      "Corn Bran Separator",
    ],
    "Grain Manufacturer": [
      "Buhler Group",
      "Satake Corporation",
      "CPM Roskamp Champion",
      "Alvan Blanch",
      "Sukup Manufacturing",
      "ArrowCorp",
      "Huantai Machinery",
      "Milleral",
    ],
  },

  "Ice-cream": {
    "Machine Name": [
      "KitchenAid Ice Cream Attachment",
      "Lello Musso Pola 5030",
      "Cuisinart ICE-100",
      "Nostalgia 4-Quart Manual",
      "Whynter ICM-15LS",
      "Elite Gourmet EIM402",
      "Cuisinart ICE-30BC",
      "Breville BCI600XL",
      "Tummbl Ice Cream Maker",
      "Ivation Automatic",
      "Ninja Creami Deluxe",
      "Breville Smart Scoop",
      "Whynter ICM-201SB",
      "Cuisinart ICE-21P1",
      "Hamilton Beach 68330N",
      "Lello 4080 Musso Lussino",
      "Nostalgia Vintage Electric",
      "YayLabs Ice Cream Ball",
      "Elite Gourmet Old Fashioned",
      "BRIOBITE ice cream maker ",
      "Carpigiani 161 T G SP",
      "Carpigiani 191 Classic",
      "Carpigiani LB 302 G RTX",
      "Carpigiani LB 502 G RTX",
      "Carpigiani Maestro HE 2",
      "Cuisinart Fresh Fruit Attachment",
      "Electro Freeze 15RMT",
      "Electro Freeze 30T-RMT",
      "Electro Freeze 44RMTFB",
      "Electro Freeze 77CMT",
      "Electro Freeze B12E",
      "Electro Freeze CS4",
      "Electro Freeze CS600",
      "Electro Freeze CS705",
      "Electro Freeze GEN-5400",
      "GSEICE Commercial Ice Cream Maker",
      "Guangshen BJ188C",
      "Guangshen BJK288S",
      "Guangshen BK3208C",
      "ICETRO SMC-303",
      "Immergood Hand Crank 8 qt",
      "Nissei NA3338 RAPID",
      "Nissei NA3348 GIANT COMBI",
      "Nissei NA6455",
      "Nissei NA9328 PROF",
      "Nissei NA9420 G SMALL ICE",
      "Nissei NA9438 POWER PRO COMBI",
      "Nissei NA9438 POWER T",
      "Oceanpower OP138",
      "Oceanpower OP138S",
      "Soft Serve Home Ice Cream Maker",
      "Spaceman 6235A-C",
      "Spaceman 6250H",
      "Spaceman 6455H",
      "Spaceman 6690",
      "Stoelting F231-309I2P",
      "Stoelting O231",
      "Stoelting SU444",
      "Taylor 0632 Combination Soft Serve & Shake Freezer",
      "Taylor 0738 Soft Serve Freezer",
      "Taylor C152",
      "Taylor C161 Compact Soft Serve Freezer",
      "Taylor C794 Soft Serve Freezer",
      "Teknoice Teknofreeze 2B",
      "Valmar Multi Chef TTi 80",
      "Valmar TTi 60",
      "VEVOR Commercial Ice Cream Maker",
    ],
    Capacity: [
      "2 quarts",
      "1.5 quarts",
      "4 quarts",
      "1 quart",
      "1.6 quarts",
      "2.1 quarts",
      "1 pint",
      "0.5 quarts",
      "5 liters",
      "12 liters (Pump Model), 18 liters (Gravity Model)",
      "15 quarts",
      "20 quarts",
      "15 liters per cycle",
      "5-quart cylinder",
      "Two 5-quart cylinders",
      "3.7-quart cylinder",
      "6 quarts per cylinder",
      "12-quart cylinder",
      "9.5-quart hopper, 2.6-quart cylinder",
      "20-quart hopper, 3.7-quart cylinder",
      "20-quart hopper, 7.7-quart cylinder",
      "5-quart cylinders, 24-quart hoppers",
      "1.6 gallons per cycle",
      "18-20 liters/hour",
      "6.8-8.4 gallons/hour",
      "30 liters/hour",
      "3.2 gallons per hour",
      "8 quarts",
      "55 liters/hour",
      "75 liters/hour",
      "50 liters per hour",
      "40 liters/hour",
      "18 liters/hour",
      "20 liters per hour",
      "1 liter",
      "5.5 gallons per hour",
      "Two 3.4-quart freezing cylinders",
      "One 8-quart cylinder",
      "20 quarts per hour",
      "Two 3-gallon hoppers",
      "5-quart cylinder, 15-gallon mix hopper",
      "8-gallon refrigerated mix storage",
      "20-quart hopper, 3.4 quarts soft serve cylinder",
      "2.1 quarts per cylinder, 8.5-quart hopper",
      "1.5 quarts per cylinder, 8-quart hopper",
      "3.4 quarts per cylinder, 14-quart hopper",
      "13 gallons/hour",
      "8 liters per cycle",
      "5.8 gallons per batch",
      "22-30 liters/hour",
    ],
  },

  Juice: {
    "Machine Name": [
      "Aeitto Slow Juicer",
      "Aicok Slow Masticating Juicer",
      "Amzchef Slow Juicer ZM1501",
      "Amzchef Slow Masticating Juicer",
      "Bagotte Centrifugal Juicer",
      "Bella High Power Juice Extractor",
      "Bextcok Slow Juicer",
      "BioChef Atlas Pro",
      "Breville Big Squeeze (BJS700SIL)",
      "Breville Bluicer Pro 3X",
      "Breville Juice Fountain Cold Plus (BJE430SIL)",
      "Breville Juice Fountain Compact",
      "Breville Juice Fountain Elite",
      "Breville Juice Fountain Plus JE98XL",
      "ChefWave CW-JE Citrus Juicer",
      "Cuisinart CCJ-500",
      "Cuisinart CJE-1000",
      "Dash Deluxe Cold Press Juicer (DCSJ255)",
      "Dash Deluxe Compact Juicer",
      "Eurolux ELCJ-1700",
      "Fohere Juicer Machine",
      "Gourmia GJ750",
      "Gourmia GMJ9970",
      "Hamilton Beach 67951 Cold Press Slow Juicer",
      "Hamilton Beach Big Mouth",
      "Hamilton Beach Premium Extractor",
      "Hamilton Beach Pro 67650",
      "Hurom H101 Easy Clean Slow Juicer",
      "Hurom H200",
      "Hurom H310 Mini",
      "Hurom H400 Easy Clean Slow Juicer",
      "Hurom H-AA Slow Juicer",
      "Hurom HZ Alpha",
      "Jack LaLanne Fusion Juicer",
      "Jocuu Slow Juicer",
      "Juiceman JM400",
      "Kensington Cold Press 16006",
      "KitchenAid JE",
      "KOIOS B5100",
      "Kuvings C7000P",
      "Kuvings CS600",
      "Kuvings EVO820 Whole Slow Juicer",
      "Kuvings REVO830 Whole Slow Juicer",
      "Kuvings Whole Slow Elite",
      "Kuvings Whole Slow Juicer Elite C7000S",
      "Magic Bullet Mini",
      "Magimix Juice Expert 3",
      "Mueller Austria Ultra Juicer",
      "Nama J1 Cold Press Juicer",
      "Ninja NeverClog JC151",
      "NutriBullet Pro Juicer",
      "NutriBullet Slow Juicer",
      "NutriChef PKSJ30",
      "Omega J8006HDS",
      "Omega MM900HDS",
      "Omega NC800HDS",
      "Omega NC900HDC",
      "Omega VSJ843QR Vertical Masticating Juicer",
      "Philips Avance HR1947/00",
      "Philips HR1889/71 Viva Masticating Juicer",
      "Pure Juicer",
      "Sage SJE430SIL",
      "Sana 707 Classic Juicer",
      "Sana 727 Supreme Juicer",
      "Sana 848 Easy Clean Juicer",
      "Sana 868 Batch Juicer",
      "Sana 878 Self-Feeding Juicer",
      "Sana 929 Stainless Steel Juicer",
      "Sana Advanced Batch Juicer",
      "Sana Commercial Citrus Press",
      "Sana Mini Juicer Pro",
      "Severin ES 3569",
      "SKG A10",
      "Smeg CJF01 Citrus Juicer",
      "SMEG SJF01",
      "Tribest Greenstar Elite GSE-5000",
      "Tribest Greenstar Pro GS-P502",
      "Tribest Shine Vertical Juicer",
      "Tribest Slowstar Vertical",
      "Tribest Solostar 4",
      "Ventray 809",
      "Ventray 870",
      "Vitamix 7800",
      "Wells 77",
      "ZENY Centrifugal Juicer",
    ],
    Material: [
      "Plastic (BPA-free)",
      "Tritan plastic (BPA-free)",
      "Steel, plastic (BPA-free)",
      "Stainless steel, plastic (BPA-free)",
      "ABS, stainless steel",
      "Tritan, steel",
      "Plastic, Tritan, steel",
      "Steel, mesh",
      "Plastic, steel (BPA-free)",
      "Metal, steel, titanium",
      "Titanium, steel",
      "Research required",
      "Steel, plastic",
      "Steel, Tritan",
      "Heavy-duty steel",
      "Stainless steel",
      "Cast iron, steel",
      "Aluminum, steel, Tritan",
    ],
    "Type of Juicer": ["Masticating", "Centrifugal"],
  },
};
